import { chromium } from "@playwright/test";
import { mkdirSync } from "node:fs";
import { startTestServer } from "./e2e-server.mjs";
mkdirSync("artifacts/redesign", { recursive: true });
const fx = await startTestServer();
await new Promise((r) => fx.server.once("listening", r));
const browser = await chromium.launch({ channel: "msedge" });
const page = await (await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true })).newPage();
const next = () => page.getByRole("button", { name: "다음", exact: true }).click();
await page.goto("http://127.0.0.1:5174/#/report/new", { waitUntil: "networkidle" });
await page.screenshot({ path: "artifacts/redesign/flow-report-1-photo.png" });
await page.locator("input[name=photo]").setInputFiles("public/assets/dog-maltese.png");
await page.getByAltText("고른 사진").waitFor();
await next();
await page.locator("input[name=name]").fill("보리");
await page.locator("input[name=breed]").fill("말티즈");
await next();
await page.screenshot({ path: "artifacts/redesign/flow-report-3-traits.png" });
await next();
await page.screenshot({ path: "artifacts/redesign/flow-report-4-when.png" });
await page.goto("http://127.0.0.1:5174/#/sighting/new/demo-bori", { waitUntil: "networkidle" });
await page.waitForTimeout(600);
await page.screenshot({ path: "artifacts/redesign/flow-sighting-1-where.png" });
await page.locator("input[name=location]").fill("석촌호수 북쪽");
await page.locator("#sighting-picker").click({ position: { x: 140, y: 100 } });
await next();
await next();
await page.getByRole("button", { name: /^이동했어요/ }).click();
await page.screenshot({ path: "artifacts/redesign/flow-sighting-3-direction.png" });
await browser.close();
await fx.close();
