-- Application-owned schema, deliberately not exposed through the public Data API.
BEGIN;
CREATE SCHEMA IF NOT EXISTS meongback;
REVOKE ALL ON SCHEMA meongback FROM PUBLIC;
CREATE TABLE IF NOT EXISTS meongback.users(id TEXT PRIMARY KEY,email TEXT UNIQUE,password TEXT,name TEXT NOT NULL,role TEXT DEFAULT 'user',verified_at BIGINT);
CREATE TABLE IF NOT EXISTS meongback.sessions(token TEXT PRIMARY KEY,user_id TEXT NOT NULL,expires BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS meongback.docs(collection TEXT NOT NULL,id TEXT NOT NULL,owner TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1,json TEXT NOT NULL,PRIMARY KEY(collection,id));
CREATE TABLE IF NOT EXISTS meongback.prefs(user_id TEXT PRIMARY KEY,json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS meongback.notices(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,json TEXT NOT NULL,sequence BIGSERIAL);
CREATE TABLE IF NOT EXISTS meongback.subscriptions(endpoint TEXT PRIMARY KEY,user_id TEXT NOT NULL,json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS meongback.config(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS meongback.outbox(id TEXT PRIMARY KEY,endpoint TEXT NOT NULL,payload TEXT NOT NULL,attempt INTEGER DEFAULT 0,next_at BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS meongback.account_tokens(token TEXT PRIMARY KEY,user_id TEXT NOT NULL,purpose TEXT NOT NULL,expires BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS meongback.rate_limits(key TEXT PRIMARY KEY,count INTEGER NOT NULL,reset_at BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS meongback.media(id TEXT PRIMARY KEY,owner TEXT NOT NULL,path TEXT NOT NULL UNIQUE,created_at BIGINT NOT NULL);
CREATE INDEX IF NOT EXISTS notices_user ON meongback.notices(user_id,sequence DESC);
CREATE INDEX IF NOT EXISTS docs_owner ON meongback.docs(owner);
CREATE INDEX IF NOT EXISTS docs_dog ON meongback.docs((json::jsonb->>'dogId')) WHERE collection='reports';
CREATE INDEX IF NOT EXISTS sessions_user ON meongback.sessions(user_id);
CREATE INDEX IF NOT EXISTS tokens_user ON meongback.account_tokens(user_id);
CREATE INDEX IF NOT EXISTS outbox_due ON meongback.outbox(next_at);
CREATE INDEX IF NOT EXISTS media_owner ON meongback.media(owner);
ALTER TABLE meongback.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE meongback.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE meongback.docs ENABLE ROW LEVEL SECURITY;
ALTER TABLE meongback.prefs ENABLE ROW LEVEL SECURITY;
ALTER TABLE meongback.notices ENABLE ROW LEVEL SECURITY;
ALTER TABLE meongback.subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE meongback.config ENABLE ROW LEVEL SECURITY;
ALTER TABLE meongback.outbox ENABLE ROW LEVEL SECURITY;
ALTER TABLE meongback.account_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE meongback.rate_limits ENABLE ROW LEVEL SECURITY;
ALTER TABLE meongback.media ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON ALL TABLES IN SCHEMA meongback FROM PUBLIC;
COMMIT;
